#Python NumPy Tutorial for Beginners


•	NumPy is essential for scientific computing and data science in Python.

•	Computers read information in bytes and Numpy uses less memory space.

•	Numpy utilizes contiguous memory for performance benefits

•	NumPy allows for item-wise computations and has various powerful applications.

•	Understanding vector dimensions and memory allocation in NumPy arrays.

•	Access and modify specific elements in a 2D NumPy array

•	Reassigning elements and indexing in NumPy arrays

•	Indexing and replacing elements in NumPy arrays

•	Generate random arrays using NumPy

•	numpy.random for generating random numbers and arrays.

•	NumPy array slicing and copying

•	Using numpy's copy function and performing element-wise arithmetic operations

•	Understanding matrix operations and multiplication

•	Numpy provides functions for performing linear algebra operations like finding the determinant and eigenvalues of a matrix.

•	Explained vertical and horizontal stacking in NumPy arrays.

•	Load data from a text file into a numpy array without using pandas

•	NumPy allows indexing with lists and performing boolean operations on arrays.

•	Boolean masking and advanced indexing in NumPy

•	Understanding the NumPy library for Python


In [ ]:
import numpy as np #numpy

In [ ]:
a=np.array([1,2,3],dtype='int32') #1d array
print(a)

[1 2 3]


In [ ]:
b=np.array([[1,2],[2,1]]) #2d array
print(b)

[[1 2]
 [2 1]]


In [ ]:
a.ndim, b.ndim #dimension

(1, 2)

In [ ]:
a.shape, b.shape #(row,col)

((3,), (2, 2))

In [ ]:
a.dtype, b.dtype #datatype

(dtype('int32'), dtype('int64'))

In [ ]:
a.itemsize, b.itemsize #itemsize (in bytes) = dtype size (in bits) / 8

(4, 8)

In [ ]:
a.size, b.size #count

(3, 4)

In [ ]:
a.nbytes, b.nbytes #nbytes = size * itemsize

(12, 32)

In [ ]:
b[1,0]

np.int64(2)

In [ ]:
b[0,:]

array([1, 2])

In [ ]:
b[:,0]

array([1, 2])

In [ ]:
b[:,0:1:1]

array([[1],
       [2]])

In [ ]:
b[1,0]=5
print(b)

[[1 2]
 [5 1]]


In [ ]:
b[:,1]=[2,5]
print(b)

[[1 2]
 [5 5]]


In [ ]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3d array
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
c[1,1,1]

np.int64(11)

In [ ]:
c[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
c[:,1,:]=[[13,14,15],[16,17,18]]
print(c)

[[[ 1  2  3]
  [13 14 15]]

 [[ 7  8  9]
  [16 17 18]]]


In [ ]:
np.zeros((2,3,3)) #zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.ones((2,3,2)) #ones

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.full((2,2),99) #full

array([[99, 99],
       [99, 99]])

In [ ]:
np.full_like(c,4) #full_like

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [ ]:
np.random.rand(4,2) #random

array([[0.87813211, 0.44114773],
       [0.83279316, 0.00365907],
       [0.00169978, 0.96146424],
       [0.83631234, 0.52763912]])

In [ ]:
np.random.random_sample(b.shape)

array([[0.42652981, 0.27223399],
       [0.41715487, 0.33321945]])

In [ ]:
np.random.randint(5,9,size=(3,3)) #random int

array([[8, 5, 8],
       [5, 6, 8],
       [7, 6, 5]])

In [ ]:
np.identity(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#repeat an array
e=np.array([[1,2,3]])
r1=np.repeat(e,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
f=e.copy() #copy
print(f)
f[0,1]=5
print(f)
print(e)

[[1 2 3]]
[[1 5 3]]
[[1 2 3]]


In [ ]:
#Math
print(f+2)
print(f-2)
print(f*2)
print(f/2)
print(f**2)
print(f+e)
print(np.sin(f))
print(np.cos(f))

[[3 7 5]]
[[-1  3  1]]
[[ 2 10  6]]
[[0.5 2.5 1.5]]
[[ 1 25  9]]
[[2 7 6]]
[[ 0.84147098 -0.95892427  0.14112001]]
[[ 0.54030231  0.28366219 -0.9899925 ]]


In [ ]:
#linear algebra
g=np.ones((2,3))
h=np.full((3,2),2)
print(g)
print(h)
print(np.matmul(g,h))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [ ]:
#determinant
i=np.identity(3)
print(np.linalg.det(i))

1.0


In [ ]:
#statistics
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(np.min(stats))
print(np.max(stats))
print(np.min(stats,axis=0))
print(np.max(stats,axis=1))
print(np.sum(stats))
print(np.sum(stats,axis=1))

1
6
[1 2 3]
[3 6]
21
[ 6 15]


In [ ]:
#recognizing array
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.vstack((v1,v2,v2)),end="\n\n") #vertically stack
print(np.hstack((v1,v2,v1))) #horizontally stack

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8 1 2 3 4]


In [ ]:
#from google.colab import files
#uploaded = files.upload()

In [ ]:
#load data from file
file1=np.genfromtxt('data.txt',delimiter=',',dtype='int32')
file1


array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [ ]:
#boolean masking and advanced indexing
file1[file1>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
np.any(file1>50,axis=0) #columnwise check

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
np.all(file1>50,axis=0) #columnwise check

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])